version: '3'
services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - '8081:8081'
    environment: {}
    networks:
      - master
networks:
  master:
    external: true