version: '3'
services:
  nexus:
    image: sonatype/nexus3:3.49.0
    container_name: nexus
    ports:
      - '8081:8081'
    environment: {}
    networks:
      - master
networks:
  master:
    external: true

# docker compose up -d
# cat /nexus-data/admin.password
# login and change admin password to "password"