scrape_configs:
  - job_name: 'kogito-app'
    scrape_interval: 2s
    metrics_path: /q/metrics
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'kogito-springboot-app'
    scrape_interval: 2s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']