version: '3'
services:
  bamoe-maven-repo:
    image: quay.io/bamoe/maven-repository:9.1.1-ibm-0003
    container_name: bamoe-maven-repo
    ports:
      - "8088:8080"
    volumes:
      - ./httpd.conf:/etc/httpd/conf/httpd.conf