version: '3'
services:
  kie_sandbox:
    container_name: kie_sandbox
    image: "quay.io/kogito_tooling_bot/kie-sandbox-image:0.16.0"
    ports:
      - 9090:8080
    environment:
      KIE_SANDBOX_EXTENDED_SERVICES_URL: "http://localhost:21345"
      KIE_SANDBOX_GIT_CORS_PROXY_URL: "http://localhost:7081"
    depends_on:
      - extended_services
      - git_cors_proxy

  extended_services:
    container_name: extended_services
    image: "quay.io/kogito_tooling_bot/kie-sandbox-extended-services-image:0.16.0"
    ports:
      - 21345:21345

  git_cors_proxy:
    container_name: git_cors_proxy
    image: "quay.io/kogito_tooling_bot/cors-proxy-image:0.16.0"
    ports:
      - 7081:8080