version: '3'
services:
  kie_canvas:
    container_name: kie_canvas
    image: "quay.io/bamoe/canvas:9.1.0-ibm-0001"
    ports:
      - 9090:8080
    environment:
      KIE_SANDBOX_EXTENDED_SERVICES_URL: "http://localhost:21345"
      KIE_SANDBOX_CORS_PROXY_URL: "http://localhost:7081"
    depends_on:
      - extended_services
      - git_cors_proxy

  extended_services:
    container_name: extended_services
    image: "quay.io/bamoe/extended-services:9.1.0-ibm-0001"
    ports:
      - 21345:21345

  git_cors_proxy:
    container_name: git_cors_proxy
    image: "quay.io/bamoe/git-cors-proxy:9.0.1"
    ports:
      - 7081:8080