version: '3'
services:
  jboss-web-server:
    image: registry.redhat.io/jboss-webserver-5/jws57-openjdk8-openshift-rhel8:5.7.2-8
    container_name: jboss-web-server
    ports:
      - '8086:8080'
    environment:
    # USAGE: RESOURCES: <prefix1>, <prefix2>, ...
    #        <prefix1>_NAME: 
    #        ...

      RESOURCES: RESOURCE
    # !!! REQUIRED !!!
      RESOURCE_NAME: jboss/datasources/sandbox-mariadb
      RESOURCE_DRIVER: org.mariadb.jdbc.Driver
      RESOURCE_TYPE: javax.sql.DataSource
      RESOURCE_FACTORY: org.apache.tomcat.jdbc.pool.DataSourceFactory
      # Define either _URL or { _PROTOCOL, _HOST, _PORT, _DATABASE }
        # If both sets are defined then URL replaces the { ... }
      RESOURCE_URL: 
        # { _PROTOCOL, _HOST, _PORT, _DATABASE }
      RESOURCE_PROTOCOL: jdbc:mariadb
      RESOURCE_HOST: mariadb
      RESOURCE_PORT: 3306
      RESOURCE_DATABASE: docker
      # Credentials
      RESOURCE_USERNAME: admin
      RESOURCE_PASSWORD: password
    # OPTIONAL
      RESOURCE_AUTH: Container
      RESOURCE_MAX_WAIT: 10000
      RESOURCE_MAX_IDLE: 30
      RESOURCE_MIN_IDLE: 
      RESOURCE_MAX_ACTIVE: 
      RESOURCE_TRANSACTION_ISOLATION: 
      RESOURCE_VALIDATION_QUERY: SELECT 1
      RESOURCE_TEST_WHEN_IDLE: true
      RESOURCE_TEST_ON_BORROW: true

      # DB_SERVICE_PREFIX_MAPPING: sandbox-postgresql=DB
      # SANDBOX_POSTGRESQL_SERVICE_HOST: postgres
      # SANDBOX_POSTGRESQL_SERVICE_PORT: 5432
      # DB_DRIVER: postgresql
      # DB_USERNAME: admin
      # DB_PASSWORD: password
      # DB_DATABASE: docker

      DB_JNDI: jboss/datasources/sandbox-mariadb

    volumes:
      - type: bind
        source: ./mounts/tomcat-jdbc.war
        target: /deployments/tomcat-jdbc.war
      - type: bind
        source: ./mounts/postgresql.jar
        target: /opt/jws-5.7/tomcat/lib/postgresql.jar
      - type: bind
        source: ./mounts/mariadb.jar
        target: /opt/jws-5.7/tomcat/lib/mariadb.jar
    networks:
    - master
networks:
  master:
    external: true

# Env Vars: https://access.redhat.com/documentation/en-us/red_hat_jboss_web_server/5.7/html/red_hat_jboss_web_server_for_openshift/jws_on_openshift_reference#ref_jws-for-openshift-compatible-environment-variables_assembly_s2i-scripts-and-maven
# For Runtime Script behaviour, check out the launch.sh and launch directory in /opt/jws-5.7/tomcat/bin directory