version: '3'
services:
  apicurio-ui:
    image: apicurio/apicurio-registry-ui:3.0.12
    container_name: apicurio-ui
    ports:
      - "8088:8080"
    environment:
      REGISTRY_API_URL: http://localhost:9091/apis/registry/v3
    networks:
      - master
  apicurio-registry:
    image: apicurio/apicurio-registry:3.0.12
    container_name: apicurio-registry
    ports:
      - "9091:8080"
    environment:
      QUARKUS_HTTP_CORS_ORIGINS: "*"
    networks:
      - master
networks:
  master:
    external: true