version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.45.6
    container_name: prometheus
    volumes:
      - ./mounts/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command: '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    networks:
      - master
networks:
  master:
    external: true