version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:13.4-alpine3.14
    ports:
      - "5432:5432"
    volumes:
      - ./mounts/sql:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "keycloak", "-U", "keycloak-user" ]
      timeout: 45s
      interval: 10s
      retries: 50
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - master

  keycloak:
    container_name: keycloak
    image: registry.redhat.io/rhbk/keycloak-rhel9:26.0
    ports:
      - "8480:8080"
      - "8443:8443"
      - "9094:9000"
    entrypoint: ["/bin/sh", "-c", 'cd /opt/keycloak && keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore && /opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh start']
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak-user
      KC_DB_PASSWORD: keycloak-pass
      KC_HOSTNAME: host.docker.internal
      KC_HTTP_PORT: 8080
      KC_HTTP_ENABLED: true
      KC_HTTP_MANAGEMENT_PORT: 9000
      KC_HEALTH_ENABLED: true
    networks:
      - master
networks:
  master:
    external: true