version: '3'
services:
  grafana:
    image: grafana/grafana:9.5.20
    container_name: grafana
    volumes:
      - ./mounts/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    networks:
      - master
networks:
  master:
    external: true