version: '3'
services:
  active-mq:
    image: registry.redhat.io/amq7/amq-broker-rhel8:7.10
    container_name: active-mq
    ports:
      - '8161:8161'
    environment:
      AMQ_USER: 'admin'
      AMQ_PASSWORD: 'password'
    networks:
    - master
networks:
  master:
    external: true