version: '3'
services:
  dd-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    restart: unless-stopped
    volumes:
      - ./mounts/conf.d/openmetrics.d/conf.yaml:/etc/datadog-agent/conf.d/openmetrics.d/conf.yaml
    environment:
      DD_API_KEY: bc79a70fb2e2cea3d0a31ff485d75d6a
      DD_SITE: "us5.datadoghq.com"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: true
      DD_HOSTNAME: dd-agent
    networks:
      - master
networks:
  master:
    external: true