version: '3'
services:
  mariadb:
    image: registry.redhat.io/rhel8/mariadb-105:1
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: password
    networks:
    - master
networks:
  master:
    external: true