version: '3'
services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: 1

  # broker:
  #   image: bitnami/kafka:3.4
  #   container_name: broker
  #   ports:
  #     - '9091:9091'
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # kafdrop:
  #   image: obsidiandynamics/kafdrop
  #   container_name: kafdrop
  #   restart: 'no'
  #   ports:
  #     - '9000:9000'
  #   environment:
  #     KAFKA_BROKERCONNECT: 'broker:29092'
  #     JVM_OPTS: '-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify'
  #   depends_on:
  #     - 'broker'