version: '3'
services:
  postgres:
    image: registry.redhat.io/rhel8/postgresql-13:1
    container_name: postgres
    ports:
      - '4321:5432'
    environment:
      POSTGRESQL_USER: admin
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: docker
      POSTGRESQL_ADMIN_PASSWORD: password
    volumes:
      - type: bind
        source: ./mounts/run-sql.sh
        target: /opt/app-root/src/postgresql-start/run-sql.sh
      - type: bind
        source: ./mounts/sql
        target: /opt/app-root/src/postgresql-start/sql
    networks:
        - master
networks:
  master:
    external: true

# Env Vars: https://catalog.redhat.com/software/containers/rhel8/postgresql-13/5ffdbdef73a65398111b8362?container-tabs=overview