version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    container_name: sqlserver
    ports:
      - '1322:1433'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password1!
      MSSQL_PID: Standard
    networks:
        - master
networks:
  master:
    external: true